### ISSUE TITLE
Criar testes para a HU: Fazer primeiro cadastro

### ISSUE THREAD

**Issue by DavidBrito** [DavidBrito/PensionApp#12]
Seguir intruções no arquivo iteração 1/Esboço Testes - BDD.md

Palavras-chave: BDD, TDD, Cucumber, Gherkins.

Responsável: Claudio

**Comment by DavidBrito** [comment]
Os testes precisam estar rodando no cucumber em um arquivo feature.

Só quando todos os testes estiverem ok a issue será fechada

**Comment by DavidBrito** [comment]
@claudiopacheco qual o andamento das atividades? Vai colocando nos comentários as coisas que você for fazendo em uma lista como a issue #24. Assim da pra saber o que você fez e o que vai fazer. 

As atividades a fazer vc cria issues pra acompanhar elas.

**Comment by claudiopacheco** [comment]
Realocação de responsabilidade para @DaironEM

**Comment by DavidBrito** [comment]
FInalizado.
