### ISSUE TITLE
Fazer Hi-Fi Mockup

### ISSUE THREAD

**Issue by DavidBrito** [DavidBrito/PensionApp#29]
Buscar sofware para fazer os Hi-Fi mockup para ajudar a já definir a identidade visual do app.

1. Reunir pessoal para definir a identidade visual do app (cores e layout)
2. Pesquisar por softwares que auxiliem nessa tarefa
3. Usar software escolhido para fazer Hi-Fi de todas* as páginas do app
4. Apresentar ao grupo para validação e feedback

* Use como base todas as histórias de usuários épicas criadas.

**Comment by adsonxzx** [comment]
Branch front-pagina-welcome
Commit: c9476f2

O que foi feito:

- criação do mockup hi fi da pagina welcome
- instalação da gem bootstrap
- implementação do front end pagina welcome

**Comment by DavidBrito** [comment]
Página welcome e dashboard feitos.
