### ISSUE TITLE
Feedback Postmortem IT3

### ISSUE THREAD

**Issue by SandrineMartins** [DavidBrito/PensionApp#44]
- Período:  data de início - data de término da iteração **OK**
- O que estava planejado: atividades e pra quem **OK**
- O que foi feito:  atividades e por quem **OK**
- O que não foi feito:  atividades e por quem, quais os impedimentos **OK**
- O que está planejado para a próxima iteração:  atividades e pra quem **OK**
- Lições aprendidas **OK**
- Entrega com um dia de atraso (-2)

### Nota: 8

**Comment by SandrineMartins** [comment]
O commit do postmortem está indicando dia 8/11
![sem titulo](https://user-images.githubusercontent.com/7128232/48436700-8642b800-e766-11e8-9332-ad78af84e039.png)

**Comment by SandrineMartins** [comment]
O commit do postmortem está indicando dia 8/11, mas creio que deva ter entrado com atraso. Vou atualizar a nota na planilha
![sem titulo](https://user-images.githubusercontent.com/7128232/48436700-8642b800-e766-11e8-9332-ad78af84e039.png)

**Comment by DavidBrito** [comment]
Muito obrigado
