### ISSUE TITLE
Feedback testes BDD e TDD IT2

### ISSUE THREAD

**Issue by joismar** [DavidBrito/PensionApp#45]
Opa! Os seguintes critérios foram avaliados nesse item:

OBS.: As features foram criadas no prazo da iteração, porém as step_definitions não. As features estão coerentes, porém, por estética sugiro criar tudo em inglês ou tudo em português. (-3)

- Coerência dos testes: Ok
- Caminhos: Ok
- Testes rodaram: Não (-3)

Nota Final: **4**

Qualquer dúvida estou disponível no Telegram. ;)

**Comment by DavidBrito** [comment]
Obrigado pela correção Joismar.

Galera, fazer as correções que foram pedidas. Atualizar as features todas em português. Usem como exemplo as features das HUs de tarefas.
