### ISSUE TITLE
Feedback IT 03 - Testes TDD e BDD

### ISSUE THREAD

**Issue by ps1312** [DavidBrito/PensionApp#53]
Ae pessoal, vou corrigir os testes da IT 03

## Testes TDD:
<ul>
  <li>Caminhos tristes e felizes: ok</li>
  <li>Cobertura de teste: ok</li>
  <li>Todos rodaram: não, alguns testes não rodaram</li>
</ul>

### Nota Final: 4
---------------------------------------------------------------

## Testes BDD:
<ul>
  <li>Caminhos tristes e felizes: ok</li>
  <li>Cobertura de teste: ok</li>
  <li>Todos rodaram: não, alguns testes não rodaram</li>
</ul>

### Nota Final: 4
---------------------------------------------------------------
Os testes tão massa, continuem assim

## Nota Final Total: 8

**Comment by DavidBrito** [comment]
Muito obrigado pelo feedback
