### ISSUE TITLE
Fazer front-end do dashboard

### ISSUE THREAD

**Issue by DavidBrito** [DavidBrito/PensionApp#66]
Usar os layouts de rails.

**Comment by adsonxzx** [comment]
Feito, da uma olhada na branch front-dashboard pra ver se ta ok

**Comment by DavidBrito** [comment]
Eu deu um olhada, a parte de usar um layout era isso mesmo.
Sobre o dashboard:
    * Tem como usar as cores base da landing page?
    * Tenta tbm reaproveitar a barra de login (header/nav) verde em todas as outras páginas?  
    * Tenta otimizar a página para desktop primeiro

De otimização, vamos tentar melhorar ao máximo a visualização para pc e notebook. tipo estipular tamanho mínimo no css.

https://www.w3schools.com/cssref/tryit.asp?filename=trycss_dim_min-width

**Comment by DavidBrito** [comment]
Dashboard feito.
