### ISSUE TITLE
Feedback Iteração 3 - Modelo ER

### ISSUE THREAD

**Issue by ps1312** [DavidBrito/PensionApp#86]
Pessoal, não encontrei o modelo ER de vcs..

**Comment by DavidBrito** [comment]
Opa, tudo bom?

O arquivo está nessa pasta, nós adiantamos na iteração 2:
[Diagrama](https://github.com/DavidBrito/PensionApp/blob/master/docs/Itera%C3%A7%C3%A3o%202/Diagrama%20ER.png)

**Comment by ps1312** [comment]
Massa, vou adicionar a nota de vcs na planilha agora
