### ISSUE TITLE
Storyboard - adicionar descrições

### ISSUE THREAD

**Issue by DaironEM** [DavidBrito/PensionApp#9]
Storyboard

Navegar através do storyboard é complicado pois não existe uma referencia clara a qual perfil se esta acessando. Alem disso tanto o botão de Efetuar Login como o de Primeiro Acesso redirecionam para a mesma "pagina".

**Comment by adsonxzx** [comment]
Corrigi lá. Essa distinção de perfil vai ser validade pelo sistema. O mesmo botão vai levar pra duas paginas distintas dependendo do perfil, não tem como colocar isso no mockup, por isso eu coloquei aqueles dois comentários que quando você clica ele vai para página do perfil adequado.
